### ISSUE TITLE
Any chance of a helm chart?

### ISSUE THREAD

**Issue by UntouchedWagons** [skybitsnl/backsnap#2]
I think it'd be very useful to have a helm chart that automatically installs all the necessary CRDs and configures the manager using data from a values.yaml.

**Comment by sgielen** [comment]
Absolutely, that would be a nice addition, I haven't gotten around to it yet. You'd be very welcome to make a PR for it.

**Comment by UntouchedWagons** [comment]
I don't have much experience making helm charts but I'll take a crack at it.

**Comment by UntouchedWagons** [comment]
Version 0.0.1 of the backsnap helm chart: https://github.com/UntouchedWagons/backsnap/tree/helm-chart/charts/apps/backsnap I think I've got the basics sorted although I haven't tried installing it onto a cluster yet.

There are other things that I think could (but not necessarily should) be added like additional labels, taints, affinities and tolerations; or custom PVCBackups and PVCRestores.

**Comment by sgielen** [comment]
Thank you @UntouchedWagons! Merged as #4.

**Comment by saggiyogesh** [comment]
Hello, can we update the docs on installation by helm chart. It will be very helpful

**Comment by sgielen** [comment]
Hi @saggiyogesh, thanks for your suggestion. I had this on my list and have gone ahead and added a "Quick start using Helm" section to the README as well as some other sections. Hopefully this is helpful, be sure to let me know if you still need help after this.
